# Generated by Django 4.0.5 on 2022-06-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('option', models.CharField(max_length=200)),
            ],
        ),
    ]
