# Generated by Django 4.0.5 on 2022-06-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_b_m_s_sest_delete_logitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='b',
            name='dir_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='m',
            name='dep_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='s',
            name='sch_type',
            field=models.IntegerField(default=0),
        ),
    ]
